# Generated by Django 4.2.20 on 2025-03-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceverifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='profile_picture',
            field=models.ImageField(upload_to='users_images/'),
        ),
    ]
