# Generated by Django 4.2.20 on 2025-03-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceverifier', '0002_alter_applicationuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='user_webapp_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
