# Generated by Django 4.2.20 on 2025-03-25 00:28

from django.db import migrations, models
import faceverifier.models


class Migration(migrations.Migration):

    dependencies = [
        ('faceverifier', '0004_clockin_applicationuser_end_work_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='foto_sended',
            field=models.ImageField(null=True, upload_to=faceverifier.models.clockin_image_upload_path),
        ),
    ]
